<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Configuration.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.1.1" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Lib.Harmony" Version="2.3.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
        <PackageReference Include="MonoMod.Backports" Version="1.1.2" />
        <PackageReference Include="MonoMod.Core" Version="1.2.1" />
        <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
        <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
        <PackageReference Include="OpenMod.UnityEngine.Redist" Version="2021.3.29.1" />
        <PackageReference Include="OpenMod.Unturned.Redist" Version="3.24.6.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LocalMod.API\LocalMod.API.csproj" />

        <Reference Include="UniTask, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\Lib\UniTask.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
