<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LocalMod.API\LocalMod.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenMod.Unturned.Redist" Version="3.24.6.1" />
    <PackageReference Include="UniTask" Version="2.5.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
